---
title: "About Me"
---

I was born and raised in Orono, Maine. I received my BA in Statistics from Harvard University in 2019, where I competed on and eventually captained the Division I Nordic Ski Team. After getting a taste of research in public health and biostatistics from undergraduate classes, I pursued an MS in Biostatistics from the Harvard Chan School of Public Health, where I worked on electronic health records-based research. In summer 2019 and summer 2020, I worked for US Ski and Snowboard as a high performance intern and Women in Sports Technology (WiST) Fellow; my research projects included visualizing force plate output, using machine learning to predicting performance from training data, and modeling medal probabilities to inform team selection criteria. Currently, I\'m a first year PhD Candidate in Biostatistics at Johns Hopkins Bloomberg School of Public Health and hope to undertake research in methods for and applications of data from wearable technology. Broadly, my interests lie at the intersection of statistics, public health, human performance, and sports science

```{}
```
